
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://nekonyuu.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Jonathan Raffre"
title: "{ Jonathan Raffre }"
description: "Blog and website of Jonathan Raffre (alias nekonyuu), babbling about all sorts of techs. Opinions expressed are mine."
keywords: "jonathan, raffre, nekonyuu, devops, cloud, data"
favicon: "/img/innovation-black.ico"

################
# Header layout #
################

black-favicon: "/img/innovation.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Design for value and simplicity, not for hype."
  - text: "Where’s your will to be different?"
  - text: "IT is in a 7 years loop, things are just simplified over and over."

# me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/nekonyuu.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: True
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/madcat.jpg"
    date: "April 2018 - January 2019"
    description: "Xebia/Sanofi - Implementing a serverless datalake with data ingestion from legacy sources"
  - image: "/img/timeline/madcat.jpg"
    date: "February 2016 - April 2018"
    description: "Xebia/Ingenico - Terminal fleet management & cart statistics from EMV card payments"
  - image: "/img/timeline/madcat.jpg"
    date: "June 2016 - October 2016"
    description: "Xebia/Accor - Deploying a Datalake based on Cloudera and integrated with Isilon"
  - image: "/img/timeline/madcat.jpg"
    date: "September 2014 - January 2016"
    description: "Xebia/AXA DIL - Location streaming from automotive devices in a reactive architecture and ML-based driving quality scoring"
  - image: "/img/timeline/yin-yang.png"
    date: "Febrary 2012 - August 2014"
    description: "Smile - SRE automating everything"
  - image: "/img/timeline/ironocto.jpg"
    date: "June 2010 - February 2012"
    description: "Entered sysadmin grounds"

# First image of the Timeline

timeline-img: "https://github.com/nekonyuu.png?size=500"

###########
# Contact #
###########

email: "jonathan@raff.re"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Jonathan is a Technical Architect, using his skillset to have a wide coverage of technical domains SRE, DevOps, Cloud, Backend and Data engineering, including some basics on data science"
author_blurb_image: "https://github.com/nekonyuu.png?size=500"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/nekonyuu42"
  - title: "github"
    url: "https://github.com/nekonyuu"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: nekonyuu
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
